### ISSUE TITLE
Missing weights in the student data.

### ISSUE THREAD

**Issue by cimentadaj** [pbiecek/PISA2012lite#4] opened 2017-02-22 17:45 UTC
Hi,

I was trying to conduct some analysis with the `student2012` data using `intsvy` and noticed that none of the `W_*` replicate weights available in all other `PISA*lite` datasets are in the `student2012` data. In fact, only `W_FSTUWT` is present but not `W_FSTR1:W_FSTR80`. Is this a mistake or am I getting something wrong here?

You can check `student2012dict` and see that the variables _are_ supposed to be there.

**Comment by pbiecek** [comment] 2017-02-22 23:00
Yes, the problem is that the dataset with replicate weights does not fit into the GitHub 100MB limit (it's 150MB).
I had to remove these columns to push rda files to GitHub. Do not know yet how to bypass this problem.

**Comment by kamilsi** [comment] 2017-02-23 08:32
Maybe put them in separate file and cbind / join as needed?

czw., 23 lut 2017 o 00:00 użytkownik Przemysław Biecek <
notifications@github.com> napisał:

**Comment by pbiecek** [comment] 2017-02-23 08:59
Brilliant idea, a separate df for weights 
will do this today

**Comment by pbiecek** [comment] 2017-02-23 14:11
@cimentadaj Please check the updated package
the following instruction should add replicate weights to  other items.

```
student2012full <- cbind(student2012, student2012weights)
```

Datasets `student2012` and `student2012weights` may be merged based on CNT/STDID/SCHID. But since rows in both datasets are in the same order, it is ok to simply cbind them.

**Comment by cimentadaj** [comment] 2017-02-24 10:32
Excellent. Thanks!

**Closed as completed** 2017-03-07 08:37 UTC
